#!/bin/bash
export path_to_ghost_install="/your/path/here/"
export blog_name="supervisorctl_blog_name"
cd ~
curl -LOk https://ghost.org/zip/ghost-latest.zip
unzip ghost-latest.zip -d ghost_temp
supervisorctl stop blog_name
cd ~
cp -R $path_to_ghost_install ghost_temp/backup
cd $path_to_ghost_install
mv  core core_backup
cd ~/ghost_temp
cp -R core $path_to_ghost_install
cp index.js *.json $path_to_ghost_install
cd content/themes/
cp -r casper $path_to_ghost_install/content/themes
cd $path_to_ghost_install
chown -R jakub_ghost:jakub_ghost *
rm -rf node_modules/
npm install --production
supervisorctl start blog_name
## if you see that everything is working properly you can remove ghost_temp folder
